image: node:16.15.1

pipelines:
    branches:
        master:
            - step:
                  name: Before Installation
                  caches:
                      - node
                  script:
                      - yarn install
                  artifacts:
                      - node_modules/** # Save modules for next steps
            - step:
                  name: Build
                  script:
                      - yarn build
                      - apt-get update && apt-get install zip
                      - mkdir app
                      - zip -r app/application.zip . -x node_modules/\* src/\* .git/\*
                  artifacts:
                      - dist/**
                      - app/**

            - step:
                name: Deploy to S3
                deployment: production
                script:
                    - pipe: atlassian/aws-s3-deploy:0.3.8
                      variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: $AWS_REGION
                        S3_BUCKET: 'analytics-consumer'
                        LOCAL_PATH: 'app'
                        ACL: 'public-read'         
                      